//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeKulubu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int ID { get; set; }
        public string BlogTitle { get; set; }
        public string BlogPictureURL { get; set; }
        public string BlogPictureSEO { get; set; }
        public string BlogContent { get; set; }
        public Nullable<System.DateTime> BlogDate { get; set; }
        public Nullable<int> BlogViewCount { get; set; }
        public Nullable<int> BlogTagsID { get; set; }
    
        public virtual Tags Tags { get; set; }
    }
}
