//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeKulubu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int ID { get; set; }
        public string EducationTitle { get; set; }
        public string EducationFileURL { get; set; }
        public string EducationFileSEO { get; set; }
        public System.DateTime EducationDate { get; set; }
        public Nullable<int> EducationView { get; set; }
        public string EducationContent { get; set; }
        public Nullable<int> EducationTypeID { get; set; }
        public Nullable<int> EducationAuthorID { get; set; }
    
        public virtual EducationType EducationType { get; set; }
    }
}
