//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeKulubu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginList
    {
        public int ID { get; set; }
        public string IPAdress { get; set; }
        public string SoftwareType { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public Nullable<int> AdminID { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
