//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeKulubu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainContents
    {
        public int ID { get; set; }
        public string facebookURL { get; set; }
        public string googleURL { get; set; }
        public string LinkedinURL { get; set; }
        public string twitterURL { get; set; }
        public string youtubeURL { get; set; }
        public string phoneNumber { get; set; }
        public string Mail { get; set; }
        public string Working1 { get; set; }
        public string Working2 { get; set; }
        public string Working3 { get; set; }
        public string fax { get; set; }
        public Nullable<int> mainofficeID1 { get; set; }
        public Nullable<int> mainofficeID2 { get; set; }
        public Nullable<int> mainofficeID3 { get; set; }
        public string ContactMessage { get; set; }
        public string contanctmainoffice { get; set; }
        public string workingcomment { get; set; }
    }
}
