//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeKulubu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficePictures
    {
        public OfficePictures()
        {
            this.Office = new HashSet<Office>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PictureID { get; set; }
        public string PictureURL { get; set; }
    
        public virtual ICollection<Office> Office { get; set; }
    }
}
