//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeKulubu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public Office()
        {
            this.OfficePictures = new HashSet<OfficePictures>();
            this.Team = new HashSet<Team>();
        }
    
        public int ID { get; set; }
        public string OfficeName { get; set; }
        public string OfficeMainContent { get; set; }
        public string OfficeAltContent { get; set; }
        public string OfficeWorkingTime { get; set; }
        public string OfficeLocation { get; set; }
        public string OfficeMail { get; set; }
        public string OfficePhone { get; set; }
    
        public virtual ICollection<OfficePictures> OfficePictures { get; set; }
        public virtual ICollection<Team> Team { get; set; }
    }
}
