//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeKulubu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proje
    {
        public int ID { get; set; }
        public string Isim { get; set; }
        public string Konum { get; set; }
        public string Tip { get; set; }
        public string Durum { get; set; }
        public Nullable<decimal> Butce { get; set; }
        public Nullable<int> Yil { get; set; }
        public string Aciklama { get; set; }
        public string SeoAlt { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string CalismaSAAT { get; set; }
        public Nullable<int> BegeniSayisi { get; set; }
        public string ResimAciklama { get; set; }
        public Nullable<int> ResimListID { get; set; }
    
        public virtual ProjeResimler ProjeResimler { get; set; }
    }
}
