//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeKulubu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ProjectPicture = new HashSet<ProjectPicture>();
            this.Team = new HashSet<Team>();
        }
    
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectBudgets { get; set; }
        public string ProjectMoneyType { get; set; }
        public string ProjectType { get; set; }
        public Nullable<int> ProjectStatusID { get; set; }
        public string ProjectYear { get; set; }
        public string ProjectLocation { get; set; }
        public string ProjectContent { get; set; }
        public string ProjectMail { get; set; }
        public string ProjectPhone { get; set; }
        public string ProjectAltLocation { get; set; }
    
        public virtual ProjectType ProjectType1 { get; set; }
        public virtual ICollection<ProjectPicture> ProjectPicture { get; set; }
        public virtual ICollection<Team> Team { get; set; }
    }
}
