//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeKulubu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjeResim
    {
        public ProjeResim()
        {
            this.Proje = new HashSet<Proje>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ResimID { get; set; }
        public string ResimAd { get; set; }
        public string ResimUrl { get; set; }
    
        public virtual ICollection<Proje> Proje { get; set; }
    }
}
