//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeKulubu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reference
    {
        public int ID { get; set; }
        public string ReferenceTitle { get; set; }
        public string ReferencePictureURL { get; set; }
        public string ReferencePictureSEO { get; set; }
        public string ReferenceLink { get; set; }
    }
}
